### ISSUE TITLE
bin folder seems to contain copy of the root folder

### ISSUE THREAD

**Issue by bbaassssiiee** [jguglielmi/OASIS-Maven#10]

**Comment by jguglielmi** [comment]
bbaassssiiee, the bin directory is created and populated by the maven dependency m2e plugin in Eclipse.  I have noticed this for a while.  I have also submitted your pull request and updated the project with the proper library locations in the install.bat and install.sh files for OJDBC.  The file is not available in Maven and is exclusive to Oracle.
