### ISSUE TITLE
Project does not compile -> /src/main/java/com/xebia/sikuli/KeyConversionFactory.java error: cannot find symbol

### ISSUE THREAD

**Issue by inico** [jguglielmi/OASIS-Maven#7]
It seems this part is not working, is there a workaround or fix available?

**Comment by jguglielmi** [comment]
As a Maven Project, we used the Maven M2E Plugin with Eclipse for ease of use.  Right click on the project, and select "Maven Update Project" which will add some dependencies to correct the issue.  I've had this one before.

Setup:
1.From a command line go to the source directory, navigate to the proper directory for OASIS-Maven, and execute "install.bat" or "install.sh".  The command should add the necessary dependencies from the plugins and lib directories to your .m2 directory
2.Open Eclipse and select File > Import > Existing Maven Projects > Next > Select the proper root directory (OASIS-Maven) > OK > Finish
3.Right click the new entry (OASIS-Maven) from the project explorer, go to Maven > Update Project > Click OK
4.Open up a command line and navigate to the OASIS-Maven directory
5.Run command "mvn -Pfitnesse test"

**Comment by inico** [comment]
I should learn to read, tried compiling without eclipse.

With eclipse it works just fine, thanks!

**Comment by jguglielmi** [comment]
Np
