### ISSUE TITLE
sikuli not finding images

### ISSUE THREAD

**Issue by inico** [jguglielmi/OASIS-Maven#9]
When building a sikuli test, the recording works, however the playback does not find the actual recorded picture.

45284 [main] ERROR com.xebia.sikuli.SikuliDriverFixture - Cannot find object: [StringTarget: searchbutton.png]
45284 [main] ERROR com.xebia.sikuli.SikuliDriverFixture - Matching was set to 0.75
45284 [main] ERROR com.xebia.sikuli.SikuliDriverFixture - Offset was set to 0 , 0

**Comment by jguglielmi** [comment]
Does it select a different image?

**Comment by inico** [comment]
How to easily verify this, is there a way to identify what sikuli found?

**Comment by jguglielmi** [comment]
inico, sorry for the late reply!  Thank you for the patch!  The fix works like a charm on my environment. I will be submitting this up in a patch with a pull request from another user.
